const roleplayingTerms = [
  "juego de rol",
  "director de juego",
  "máster",
  "Dungeon Master",
  "Game Master",
  "jugador",
  "personaje",
  "personaje jugador",
  "personaje no jugador",
  "PJ",
  "PNJ",
  "NPC",
  "campaña",
  "aventura",
  "sesión",
  "escena",
  "misión",
  "grupo",
  "mesa",
  "interpretación",
  "trasfondo",
  "iniciativa",
  "tirada",
  "tirada de dados",
  "dado de veinte",
  "dado de seis",
  "crítico",
  "pifia",
  "ventaja",
  "desventaja",
  "dificultad",
  "combate",
  "turno",
  "ronda",
  "acción",
  "reacción",
  "movimiento",
  "ataque",
  "defensa",
  "daño",
  "curación",
  "puntos de vida",
  "armadura",
  "hechizo",
  "nivel",
  "experiencia",
  "inventario",
  "mapa",
  "mazmorra",
  "taberna",
  "dragón",
] as const;

// Compact Chilean vocabulary selected from Wikcionario's ES:Chile category.
// Keep variants that are genuinely useful in conversational tabletop audio;
// the complete dictionary is far too large and would bias Whisper.
const chileanSpanishTerms = [
  "cachái",
  "al tiro",
  "bacán",
  "fome",
  "piola",
  "cuático",
  "brígido",
  "caleta",
  "filo",
  "pucha",
  "weón",
  "hueón",
  "weá",
  "hueá",
  "lesear",
  "leseando",
  "achuntar",
  "apañar",
  "pololo",
  "pega",
  "carrete",
  "copete",
] as const;

// Spanish terminology from the official SRD 5.2.1. These are high-value
// phrases that Whisper commonly splits or replaces with ordinary words.
const dndTerms = [
  "D&D",
  "Dungeons & Dragons",
  "Dungeon Master",
  "d20",
  "clase de armadura",
  "puntos de golpe",
  "prueba de característica",
  "tirada de ataque",
  "tirada de salvación",
  "bonificador por competencia",
  "clase de dificultad",
  "acción adicional",
  "ataque de oportunidad",
  "descanso corto",
  "descanso largo",
  "dado de golpe",
  "espacio de conjuro",
  "nivel de conjuro",
  "concentración",
  "truco",
  "ritual",
  "resistencia mágica",
  "daño contundente",
  "daño cortante",
  "daño perforante",
  "inspiración heroica",
  "estado derribado",
  "estado apresado",
] as const;

const dottyTerms = [
  "Dotty",
  "Discord",
  "bot",
  "canal de voz",
  "canal de texto",
  "Foro",
  "publicación",
  "transcripción",
  "bitácora",
  "Dotty configurar",
  "Dotty iniciar",
  "Dotty pausar",
  "Dotty reanudar",
  "Dotty finalizar",
  "Dotty personaje",
  "Dotty personajes",
  "Dotty sesiones",
  "Dotty vocabulario",
  "Dotty reprocesar",
  "Dotty borrar sesión",
  "Dotty borrar personaje",
  "Dotty borrar campaña",
] as const;

export function baseTranscriptionVocabulary(): string {
  return [...new Set([
    ...dottyTerms,
    ...roleplayingTerms,
    ...dndTerms,
    ...chileanSpanishTerms,
  ])].join(", ");
}

/**
 * Small default set sent directly to Whisper. Campaign names, character names
 * and user corrections are placed before it by the dispatcher and therefore
 * remain the highest-priority vocabulary.
 */
export function priorityTranscriptionHotwords(): readonly string[] {
  return [
    "cachái",
    "al tiro",
    "bacán",
    "fome",
    "piola",
    "cuático",
    "brígido",
    "caleta",
    "weón",
    "hueón",
    "weá",
    "hueá",
    "D&D",
    "Dungeons & Dragons",
    "Dungeon Master",
    "d20",
    "clase de armadura",
    "puntos de golpe",
    "tirada de salvación",
    "acción adicional",
    "ataque de oportunidad",
    "espacio de conjuro",
    "concentración",
    "PNJ",
  ];
}
